@IO.Server_HostAddress = http://localhost:5110

GET {{IO.Server_HostAddress}}/api/main/getEnvUsers
Accept: application/json

###

POST {{IO.Server_HostAddress}}/api/login/loginRequest
Content-Type: application/json
{
    "Username": "Admin",
    "Password": "*******"
}
###
GET {{IO.Server_HostAddress}}/api/main/getEnvCourses
Accept: application/json

###

GET {{IO.Server_HostAddress}}/api/CoursesManager/Student/44/courses
Accept: application/json

###

GET {{IO.Server_HostAddress}}/api/TestManager/TestsList/5/tests
Accept: application/json

###

GET {{IO.Server_HostAddress}}/api/CoursesManager/AddUsersList/49
Accept: application/json

###


