@IO.Server_HostAddress = http://localhost:5110

GET {{IO.Server_HostAddress}}/api/main
Accept: application/json

###

POST {{IO.Server_HostAddress}}/api/login/loginRequest
Content-Type: application/json
{
    "Username": "testLogin",
    "Password": "1234"
}
###